### ISSUE TITLE
Using variable from external file interferes with buffer flip.

### ISSUE THREAD

**Issue by gety9** [killdash9/buffer-flip.el#10]
I have following code block in org-mode:

```
#+BEGIN_SRC python :var a=localtable b=folder/my-externalfile:externaltable :results value table :return rtn
import scripts.myscript as ms
rtn = ms.myfunction(b)
#+END_SRC
```

any time i evaluate the code block it puts my-externalfile top into buffer-flip (as if i just switched from that external file).

example say i flip between buffer1 (where above code block is) and buffer 2 (buffer1 > buffer2 > buffer 1 > buffer 2, etc), but when i evaluate the code buffer flip becomes (buffer 1 > my-externalfile > buffer 1 > my-externalfile)

If i remove external table variable

```
#+BEGIN_SRC python :var a=localtable :results value table :return rtn
import scripts.myscript as ms
rtn = ms.myfunction(a)
#+END_SRC
```

and if i evalute the code buffer flip works correctly.

---

My config:

```
  :config
  (setq buffer-flip-skip-patterns
        '("^\\*scratch\\*$"
	  "^\\*Messages\\*$"
	  "^\\*Org-Babel Error Output\\*$")
```

**Comment by killdash9** [comment]
What do you see when you run `M-x list-buffers`?  I'm guessing that running the python script is temporarily switching to the my-externalfile buffer, which places it on the buffer stack.

**Comment by killdash9** [comment]
You could tell buffer-flip to skip my-external file with `M-x customize-variable RET buffer-flip-skip-patterns`

**Comment by gety9** [comment]
Thank you for fast reply

list-buffers shows my-external file as 2nd from top after evaluating the code. It's not caused by my python script switching to my-external buffer (it's same behavior with print ("hello world")) but by org-mode "looking up" variable. 

I will close the issue and will write to org-mode email list maybe they will fix it.
