### ISSUE TITLE
Is it possible for not using key-chord mode to do buffer-flip?

### ISSUE THREAD

**Issue by cmal** [killdash9/buffer-flip.el#4]
`buffer-flip` provides an amazing buffer-switching feature.
I don't like `key-chord` and want to write another package to do this. But I am not so familiar with elisp.
I am wondering is there a reason why you choose to use `key-chord` to do this job at the time this package was writing? 
Is it possible for not using key-chord mode to do buffer-flip? And further, is it possible for elisp to define M-<tab> to switch to the top buffer on stack, and following <tab>s to switch to following buffers on stack? and when Meta key is up, it return to the current-buffer when calling this command, unless a <ret> was pressed when Meta key was still down?
Any advice would be helpful. Thank you!

**Comment by pheaver** [comment]
I have the same question. This package is perfect for me, except I don't think I want to use key-chord.

**Comment by cmal** [comment]
@pheaver :handshake:  I don't use key-chord because I have problems when using key-chord.

**Comment by killdash9** [comment]
This is addressed in the most recent release (2.0).  Normal key bindings can now be used with this library.  See Readme for details.

**Comment by killdash9** [comment]
Fixed in 868aa9e04438d57746e0b1f5a13bcb9b64061c05
