### ISSUE TITLE
<M-iso-lefttab> is undefined 

### ISSUE THREAD

**Issue by pseudomyne** [killdash9/buffer-flip.el#6]
Hi. 
♥ your package. I just can't `buffer-flip-backward`with `M-S-<tab>.`, getting `<M-iso-lefttab> is undefined`. 
It isn't related to your package because another binding works.
Maybe you'd have an idea.. 
Rolling Archlinux here, with bspwm / sxhkd as WM with fr layout (may be related)

**Comment by killdash9** [comment]
@pseudomyne have you been able to get this working?

**Comment by pataquets** [comment]
Same here.
Ubuntu Bionic, i3wm, es-CA layout.

**Comment by killdash9** [comment]
@pataquets what error do you see, and can you share your buffer-flip config?

**Comment by pseudomyne** [comment]
> 

Hi, yes. Added this to my config : 

`(define-key function-key-map [(meta shift iso-lefttab)] [(meta shift tab)])
`

**Comment by killdash9** [comment]
That doesn't look like your buffer-flip config.  I'm looking for something like this:

```
(setq buffer-flip-map
      (let ((map (make-sparse-keymap)))
        (define-key map (kbd "M-<tab>")   'buffer-flip-forward) 
        (define-key map (kbd "M-S-<tab>") 'buffer-flip-backward)
        (define-key map (kbd "M-ESC")     'buffer-flip-abort)
        map))
```

**Comment by pseudomyne** [comment]
The line I gave you is **what makes the binding work**, just before my config, which is almost the same : 
```
(use-package buffer-flip
  :ensure t
  :bind  (("M-<tab>" . buffer-flip)
          :map buffer-flip-map
          ( "M-<tab>" .   buffer-flip-forward) 
          ( "M-S-<tab>" . buffer-flip-backward)
	  ( "M-²" . buffer-flip-backward) 
          ( "M-ESC" .     buffer-flip-abort))
  :config
  (setq buffer-flip-skip-patterns
        '("^\\*helm\\b"
          "^\\*swiper\\*$")))
```

**Comment by killdash9** [comment]
Glad to hear you got it working.
